# hsv_filter_node:
#   ros__parameters:
#     use_sim_time: true
#     min_h: 146
#     max_h: 180
#     min_s: 200
#     max_s: 215
#     min_v: 182
#     max_v: 255

hsv_filter_node:
  ros__parameters:
    use_sim_time: true
    min_h: 94
    max_h: 97
    min_s: 150
    max_s: 170
    min_v: 98
    max_v: 224

detection_to_3d_from_depth_node:
  ros__parameters:
    use_sim_time: true

